# -*- coding: utf-8 -*-
"""Exercicio - Calculadora

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i8E35robjiHWFP3b6XDYTxpwP6XimGZu
"""

#calculadora phyton

def soma (a, b):
  return a + b
  pass

def subtracao (a, b):
  return a - b
  pass

def multiplicacao (a, b):
  return a * b
  pass

def divisao (a, b):
  if b == 0:
    return "Erro divisao por zero"
  else:
    return a / b

def potenciacao (a, b):
  return a ** b

def calculadora():
  print("Vamos calcular")

def definir_menu():
  print("Opcoes")
  print("1 - Soma")
  print("2 - Subtracao")
  print("3 - Multiplicacao")
  print("4 - Divisao")
  print("5 - Potenciacao")
  print("6 - Sair")

option = input ("Escolha uma opcao: ")

if option == "5":
  print("Obrigada")


if option not in ["1", "2", "3", "4"]:
  print("opcao invalida, selecione uma opcao valida")


numero1 = float(input("Digite o primeiro numero: "))
numero2 = float(input("Digite o segundo numero: "))

if option =="1":
  result = soma(numero1, numero2)
  print("O resultado e {}".format(result))
elif option =="2":
  result = subtracao(numero1, numero2)
  print("O resultado e {}".format(result))
elif option =="3":
  result = multiplicacao(numero1, numero2)
  print("O resultado e {}".format(result))
elif option =="4":
  result = divisao(numero1, numero2)
  print("O resultado e {}".format(result))
elif option =="5":
  result = potenciacao(numero1, numero2)
  print("O resultado e {}".format(result))
else:
  pass

calculadora()